apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolldice
  template:
    metadata:
      labels:
        app: rolldice
    spec:
      containers:
        - name: rolldice
          image: ghcr.io/signoz/sample-rolldice:latest
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://10.172.27.18:4317"
            - name: OTEL_SERVICE_NAME
              value: "rolldice"
